In [22]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
import optuna

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [23]:
df = pd.read_csv('../Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [24]:
df.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Amount Paid', 'Is Laundering',
       'Amount_Received_USD', 'Amount_Paid_USD',
       ...
       'Payment Currency_Yuan', 'Payment Format_ACH', 'Payment Format_Bitcoin',
       'Payment Format_Cash', 'Payment Format_Cheque',
       'Payment Format_Credit Card', 'Payment Format_Reinvestment',
       'Payment Format_Wire', 'Account_Same', 'Bank_Same'],
      dtype='object', length=109)

In [25]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5078345 entries, 0 to 5078344
Columns: 104 entries, Amount Received to Bank_Same
dtypes: float64(101), int64(3)
memory usage: 3.9 GB

In [27]:
random_state = 42

## Baseline Model on Entire Dataset

In [28]:
X = df.drop(columns='Is Laundering')
y = df['Is Laundering']

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Default settings on RF

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    random_state=random_state,
    n_jobs=-1,
)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [31]:
y_pred = model.predict(X_test)

In [32]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1014634
           1       0.13      0.08      0.10      1035

    accuracy                           1.00   1015669
   macro avg       0.57      0.54      0.55   1015669
weighted avg       1.00      1.00      1.00   1015669

In [33]:
baseline_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### Class Weight Balanced

In [34]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    random_state=random_state,
    n_jobs=-1
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [35]:
y_pred = model.predict(X_test)

In [36]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1014634
           1       0.05      0.08      0.06      1035

    accuracy                           1.00   1015669
   macro avg       0.53      0.54      0.53   1015669
weighted avg       1.00      1.00      1.00   1015669

In [37]:
baseline_balanced_model_report_df = classification_report(y_test, y_pred, output_dict=True)

## Undersampling due to Class Imbalance

In [38]:
fraud = df[df['Is Laundering'] == 1]
non_fraud = df[df['Is Laundering'] == 0]
len(fraud), len(non_fraud)

(5177, 5073168)

In [39]:
# Undersample majority class to a 1:10 ratio
non_fraud_downsampled = non_fraud.sample(n=len(fraud) * 10, random_state=random_state)
non_fraud_downsampled

,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,US Dollar_Amount_Paid_Mean,US Dollar_Amount_Paid_Median,US Dollar_Amount_Received_Mean,US Dollar_Amount_Received_Median,Bitcoin_Amount_Paid_Mean,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
4563287,1439.79,1439.79,0,3.829841e+02,3.829841e+02,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
4216770,33.09,33.09,0,3.309000e+01,3.309000e+01,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
2992877,263.34,263.34,0,3.807896e+01,3.807896e+01,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1499016,17154983.76,17154983.76,0,1.747064e+07,1.747064e+07,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
510282,8499.22,8499.22,0,2.501320e+03,2.501320e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3992741,5722.87,5722.87,0,5.722870e+03,5.722870e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
44465,82208.92,82208.92,0,8.220892e+04,8.220892e+04,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
1173046,6837.09,6837.09,0,5.196872e+03,5.196872e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
4125810,3261.27,3261.27,0,3.763506e+03,3.763506e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
3821365,20287.92,20287.92,0,2.933633e+03,2.933633e+03,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [40]:
# Combine and shuffle
df_reduced = pd.concat([fraud, non_fraud_downsampled]).sample(frac=1).reset_index(drop=True)
df_reduced

,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,US Dollar_Amount_Paid_Mean,US Dollar_Amount_Paid_Median,US Dollar_Amount_Received_Mean,US Dollar_Amount_Received_Median,Bitcoin_Amount_Paid_Mean,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,184531.22,184531.22,1,1310.171662,1310.171662,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,3935.63,3935.63,0,4008.045592,4008.045592,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0
2,13507.02,13507.02,1,13432.731390,13432.731390,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
3,346.45,346.45,0,92.155700,92.155700,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
4,465.90,465.90,0,465.900000,465.900000,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56942,321.04,321.04,0,94.482072,94.482072,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0
56943,548.67,548.67,0,372.492063,372.492063,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
56944,128746.41,128746.41,0,1609.330125,1609.330125,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
56945,1157.02,1157.02,1,1150.656390,1150.656390,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
56946,950.76,950.76,0,1097.177040,1097.177040,367153.780541,904.13,4.041979e+06,908.2,20.809275,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0

In [41]:
X = df_reduced.drop(columns='Is Laundering')
y = df_reduced['Is Laundering']

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

In [43]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

### RF With unscaled Data and recall as param tuning metric

In [44]:
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

unscaled_df = study.trials_dataframe().sort_values("value", ascending=False)
top_5_unscaled_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_unscaled_df)

[I 2026-04-14 18:56:32,741] A new study created in memory with name: no-name-17fe4f62-987c-4b9c-a003-2a0baa777005
[I 2026-04-14 18:56:38,150] Trial 0 finished with value: 0.7875491687208266 and parameters: {'n_estimators': 99, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 0 with value: 0.7875491687208266.
[I 2026-04-14 18:56:40,722] Trial 1 finished with value: 0.8107235887484485 and parameters: {'n_estimators': 166, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.8107235887484485.
[I 2026-04-14 18:56:43,120] Trial 2 finished with value: 0.818208889121985 and parameters: {'n_estimators': 72, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 2 with value: 0.818208889121985.
[I 2026-04-14 18:56:45,437] Trial 3 finished with value: 0.8107238801186458 and parameters: {'n_estimators': 103, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 2 with value: 0.818208889121985.
[I 2026-04-14 18:56:46,726] Trial 4 finished with value: 0.8085511325559576 and parameters: {'n_estimators': 137, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 2 with value: 0.818208889121985.
[I 2026-04-14 18:56:47,138] Trial 5 finished with value: 0.8269115341806378 and parameters: {'n_estimators': 11, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 5 with value: 0.8269115341806378.
[I 2026-04-14 18:56:48,500] Trial 6 finished with value: 0.8145862834565829 and parameters: {'n_estimators': 119, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 5 with value: 0.8269115341806378.
[I 2026-04-14 18:56:52,023] Trial 7 finished with value: 0.8389695984335939 and parameters: {'n_estimators': 141, 'max_depth': 13, 'min_samples_split': 6}. Best is trial 7 with value: 0.8389695984335939.
[I 2026-04-14 18:56:52,693] Trial 8 finished with value: 0.8075869885724607 and parameters: {'n_estimators': 54, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 7 with value: 0.8389695984335939.
[I 2026-04-14 18:56:53,863] Trial 9 finished with value: 0.7370885124385937 and parameters: {'n_estimators': 27, 'max_depth': 26, 'min_samples_split': 6}. Best is trial 7 with value: 0.8389695984335939.
[I 2026-04-14 18:56:58,530] Trial 10 finished with value: 0.8413847660005944 and parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 10 with value: 0.8413847660005944.
[I 2026-04-14 18:57:03,020] Trial 11 finished with value: 0.8459718070196909 and parameters: {'n_estimators': 190, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 11 with value: 0.8459718070196909.
[I 2026-04-14 18:57:06,812] Trial 12 finished with value: 0.8491095726764684 and parameters: {'n_estimators': 193, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 12 with value: 0.8491095726764684.
[I 2026-04-14 18:57:11,092] Trial 13 finished with value: 0.8486264808890287 and parameters: {'n_estimators': 200, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 12 with value: 0.8491095726764684.
[I 2026-04-14 18:57:14,254] Trial 14 finished with value: 0.8515238661328765 and parameters: {'n_estimators': 169, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:16,383] Trial 15 finished with value: 0.8447629120703019 and parameters: {'n_estimators': 158, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:19,249] Trial 16 finished with value: 0.8500751735109526 and parameters: {'n_estimators': 172, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:21,934] Trial 17 finished with value: 0.8495923730937104 and parameters: {'n_estimators': 165, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:26,540] Trial 18 finished with value: 0.8049302751117404 and parameters: {'n_estimators': 140, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:29,234] Trial 19 finished with value: 0.8503167194046723 and parameters: {'n_estimators': 173, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:30,837] Trial 20 finished with value: 0.8507995198219145 and parameters: {'n_estimators': 85, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:32,443] Trial 21 finished with value: 0.8507995198219145 and parameters: {'n_estimators': 82, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:34,222] Trial 22 finished with value: 0.8500757562513476 and parameters: {'n_estimators': 78, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:36,694] Trial 23 finished with value: 0.8288302069311142 and parameters: {'n_estimators': 80, 'max_depth': 16, 'min_samples_split': 10}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:37,673] Trial 24 finished with value: 0.8165198160871314 and parameters: {'n_estimators': 62, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:38,786] Trial 25 finished with value: 0.8476611714247418 and parameters: {'n_estimators': 46, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:40,157] Trial 26 finished with value: 0.8179673432282654 and parameters: {'n_estimators': 90, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:43,503] Trial 27 finished with value: 0.8348653578317394 and parameters: {'n_estimators': 119, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 14 with value: 0.8515238661328765.
[I 2026-04-14 18:57:45,716] Trial 28 finished with value: 0.8520072492905136 and parameters: {'n_estimators': 120, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:50,203] Trial 29 finished with value: 0.746265799548959 and parameters: {'n_estimators': 119, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:51,253] Trial 30 finished with value: 0.8160370156698893 and parameters: {'n_estimators': 95, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:53,221] Trial 31 finished with value: 0.8520069579203161 and parameters: {'n_estimators': 105, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:54,937] Trial 32 finished with value: 0.8462116046922257 and parameters: {'n_estimators': 109, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:57,315] Trial 33 finished with value: 0.8515241575030739 and parameters: {'n_estimators': 131, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:57:59,453] Trial 34 finished with value: 0.8464537333263404 and parameters: {'n_estimators': 149, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:03,339] Trial 35 finished with value: 0.8334157910992233 and parameters: {'n_estimators': 133, 'max_depth': 15, 'min_samples_split': 9}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:06,267] Trial 36 finished with value: 0.8474193341608247 and parameters: {'n_estimators': 127, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:07,188] Trial 37 finished with value: 0.8087929698198749 and parameters: {'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:12,689] Trial 38 finished with value: 0.6733515731076962 and parameters: {'n_estimators': 149, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:13,879] Trial 39 finished with value: 0.8177260887047428 and parameters: {'n_estimators': 101, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 28 with value: 0.8520072492905136.
[I 2026-04-14 18:58:17,233] Trial 40 finished with value: 0.8524894669673607 and parameters: {'n_estimators': 184, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:20,390] Trial 41 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 182, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:23,900] Trial 42 finished with value: 0.8515238661328765 and parameters: {'n_estimators': 183, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:26,588] Trial 43 finished with value: 0.8471777882671049 and parameters: {'n_estimators': 184, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:30,165] Trial 44 finished with value: 0.842591621358601 and parameters: {'n_estimators': 156, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:31,961] Trial 45 finished with value: 0.8271411338962606 and parameters: {'n_estimators': 127, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:35,765] Trial 46 finished with value: 0.850799811192112 and parameters: {'n_estimators': 178, 'max_depth': 10, 'min_samples_split': 8}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:37,913] Trial 47 finished with value: 0.8520072492905136 and parameters: {'n_estimators': 120, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:40,029] Trial 48 finished with value: 0.8406601283194348 and parameters: {'n_estimators': 70, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:41,256] Trial 49 finished with value: 0.8131387563154491 and parameters: {'n_estimators': 107, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:43,726] Trial 50 finished with value: 0.8493514099403857 and parameters: {'n_estimators': 145, 'max_depth': 7, 'min_samples_split': 6}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:46,057] Trial 51 finished with value: 0.8515244488732714 and parameters: {'n_estimators': 126, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:48,797] Trial 52 finished with value: 0.8469374078541752 and parameters: {'n_estimators': 117, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:51,891] Trial 53 finished with value: 0.850799811192112 and parameters: {'n_estimators': 162, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:53,354] Trial 54 finished with value: 0.8447637861808943 and parameters: {'n_estimators': 97, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:55,461] Trial 55 finished with value: 0.8520072492905136 and parameters: {'n_estimators': 115, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:58:57,320] Trial 56 finished with value: 0.849592664463908 and parameters: {'n_estimators': 111, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:01,298] Trial 57 finished with value: 0.8500754648811502 and parameters: {'n_estimators': 193, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:02,009] Trial 58 finished with value: 0.8058976241674097 and parameters: {'n_estimators': 34, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:04,230] Trial 59 finished with value: 0.8418675664178366 and parameters: {'n_estimators': 89, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:06,789] Trial 60 finished with value: 0.851282611609354 and parameters: {'n_estimators': 153, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:09,345] Trial 61 finished with value: 0.8515241575030739 and parameters: {'n_estimators': 136, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:11,621] Trial 62 finished with value: 0.8498342103576277 and parameters: {'n_estimators': 125, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:13,938] Trial 63 finished with value: 0.8515241575030739 and parameters: {'n_estimators': 117, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:15,560] Trial 64 finished with value: 0.8457290956451811 and parameters: {'n_estimators': 104, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:18,558] Trial 65 finished with value: 0.8503173021450674 and parameters: {'n_estimators': 139, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:20,470] Trial 66 finished with value: 0.8515238661328766 and parameters: {'n_estimators': 95, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:22,347] Trial 67 finished with value: 0.8498342103576277 and parameters: {'n_estimators': 112, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:24,344] Trial 68 finished with value: 0.8442795289126648 and parameters: {'n_estimators': 126, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:28,174] Trial 69 finished with value: 0.8505585566685896 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:31,369] Trial 70 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 175, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:34,730] Trial 71 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 186, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:37,715] Trial 72 finished with value: 0.8505576825579972 and parameters: {'n_estimators': 175, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:42,304] Trial 73 finished with value: 0.8471786623776973 and parameters: {'n_estimators': 187, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:45,889] Trial 74 finished with value: 0.8522485038140359 and parameters: {'n_estimators': 179, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:49,570] Trial 75 finished with value: 0.8503167194046723 and parameters: {'n_estimators': 169, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:53,095] Trial 76 finished with value: 0.8522485038140359 and parameters: {'n_estimators': 178, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 18:59:57,627] Trial 77 finished with value: 0.8401770365319953 and parameters: {'n_estimators': 178, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:01,479] Trial 78 finished with value: 0.8517659947669912 and parameters: {'n_estimators': 192, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:05,324] Trial 79 finished with value: 0.8503167194046723 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:07,656] Trial 80 finished with value: 0.8483846436251113 and parameters: {'n_estimators': 164, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:10,770] Trial 81 finished with value: 0.8520069579203161 and parameters: {'n_estimators': 170, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:13,917] Trial 82 finished with value: 0.8507992284517172 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:17,377] Trial 83 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 195, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:21,817] Trial 84 finished with value: 0.8466958619604552 and parameters: {'n_estimators': 198, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:25,592] Trial 85 finished with value: 0.8520072492905136 and parameters: {'n_estimators': 195, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:28,768] Trial 86 finished with value: 0.8503161366642775 and parameters: {'n_estimators': 189, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:32,964] Trial 87 finished with value: 0.8433156762993654 and parameters: {'n_estimators': 175, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:36,744] Trial 88 finished with value: 0.8517657033967938 and parameters: {'n_estimators': 184, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:39,146] Trial 89 finished with value: 0.8466949878498629 and parameters: {'n_estimators': 161, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:42,508] Trial 90 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 178, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:45,877] Trial 91 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 181, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:48,966] Trial 92 finished with value: 0.8503167194046725 and parameters: {'n_estimators': 179, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:50,174] Trial 93 finished with value: 0.8104820428547287 and parameters: {'n_estimators': 169, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:52,604] Trial 94 finished with value: 0.8411420546260846 and parameters: {'n_estimators': 189, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.
[I 2026-04-14 19:00:55,804] Trial 95 finished with value: 0.8522482124438383 and parameters: {'n_estimators': 173, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 40 with value: 0.8524894669673607.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
40,40,0.852489,2026-04-14 18:58:13.881564,2026-04-14 18:58:17.233389,0 days 00:00:03.351825,8,9,184,COMPLETE
74,74,0.852249,2026-04-14 18:59:42.305495,2026-04-14 18:59:45.889757,0 days 00:00:03.584262,9,10,179,COMPLETE
76,76,0.852249,2026-04-14 18:59:49.571348,2026-04-14 18:59:53.095867,0 days 00:00:03.524519,9,10,178,COMPLETE
41,41,0.852248,2026-04-14 18:58:17.234391,2026-04-14 18:58:20.390099,0 days 00:00:03.155708,8,9,182,COMPLETE
83,83,0.852248,2026-04-14 19:00:13.918548,2026-04-14 19:00:17.376644,0 days 00:00:03.458096,8,10,195,COMPLETE

In [45]:
top_5_unscaled_df

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
40,40,0.852489,2026-04-14 18:58:13.881564,2026-04-14 18:58:17.233389,0 days 00:00:03.351825,8,9,184,COMPLETE
74,74,0.852249,2026-04-14 18:59:42.305495,2026-04-14 18:59:45.889757,0 days 00:00:03.584262,9,10,179,COMPLETE
76,76,0.852249,2026-04-14 18:59:49.571348,2026-04-14 18:59:53.095867,0 days 00:00:03.524519,9,10,178,COMPLETE
41,41,0.852248,2026-04-14 18:58:17.234391,2026-04-14 18:58:20.390099,0 days 00:00:03.155708,8,9,182,COMPLETE
83,83,0.852248,2026-04-14 19:00:13.918548,2026-04-14 19:00:17.376644,0 days 00:00:03.458096,8,10,195,COMPLETE

In [61]:
unscaled_df

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
40,40,0.852489,2026-04-14 18:58:13.881564,2026-04-14 18:58:17.233389,0 days 00:00:03.351825,8,9,184,COMPLETE
74,74,0.852249,2026-04-14 18:59:42.305495,2026-04-14 18:59:45.889757,0 days 00:00:03.584262,9,10,179,COMPLETE
76,76,0.852249,2026-04-14 18:59:49.571348,2026-04-14 18:59:53.095867,0 days 00:00:03.524519,9,10,178,COMPLETE
41,41,0.852248,2026-04-14 18:58:17.234391,2026-04-14 18:58:20.390099,0 days 00:00:03.155708,8,9,182,COMPLETE
83,83,0.852248,2026-04-14 19:00:13.918548,2026-04-14 19:00:17.376644,0 days 00:00:03.458096,8,10,195,COMPLETE
95,95,0.852248,2026-04-14 19:00:52.605823,2026-04-14 19:00:55.804059,0 days 00:00:03.198236,8,9,173,COMPLETE
70,70,0.852248,2026-04-14 18:59:28.175511,2026-04-14 18:59:31.369146,0 days 00:00:03.193635,8,10,175,COMPLETE
71,71,0.852248,2026-04-14 18:59:31.370149,2026-04-14 18:59:34.730109,0 days 00:00:03.359960,8,10,186,COMPLETE
91,91,0.852248,2026-04-14 19:00:42.509170,2026-04-14 19:00:45.877642,0 days 00:00:03.368472,8,9,181,COMPLETE
90,90,0.852248,2026-04-14 19:00:39.147655,2026-04-14 19:00:42.508169,0 days 00:00:03.360514,8,9,178,COMPLETE
55,55,0.852007,2026-04-14 18:58:53.356900,2026-04-14 18:58:55.461728,0 days 00:00:02.104828,8,9,115,COMPLETE
47,47,0.852007,2026-04-14 18:58:35.766773,2026-04-14 18:58:37.913393,0 days 00:00:02.146620,8,10,120,COMPLETE
28,28,0.852007,2026-04-14 18:57:43.505262,2026-04-14 18:57:45.716503,0 days 00:00:02.211241,8,6,120,COMPLETE
85,85,0.852007,2026-04-14 19:00:21.818471,2026-04-14 19:00:25.592370,0 days 00:00:03.773899,9,10,195,COMPLETE
81,81,0.852007,2026-04-14 19:00:07.656425,2026-04-14 19:00:10.770419,0 days 00:00:03.113994,8,10,170,COMPLETE
98,98,0.852007,2026-04-14 19:01:03.209647,2026-04-14 19:01:06.886281,0 days 00:00:03.676634,8,9,195,COMPLETE
31,31,0.852007,2026-04-14 18:57:51.254054,2026-04-14 18:57:53.221626,0 days 00:00:01.967572,8,6,105,COMPLETE
78,78,0.851766,2026-04-14 18:59:57.628826,2026-04-14 19:00:01.479854,0 days 00:00:03.851028,9,10,192,COMPLETE
88,88,0.851766,2026-04-14 19:00:32.965790,2026-04-14 19:00:36.744175,0 days 00:00:03.778385,9,10,184,COMPLETE
51,51,0.851524,2026-04-14 18:58:43.728050,2026-04-14 18:58:46.057055,0 days 00:00:02.329005,8,9,126,COMPLETE
61,61,0.851524,2026-04-14 18:59:06.791387,2026-04-14 18:59:09.345765,0 days 00:00:02.554378,8,9,136,COMPLETE
63,63,0.851524,2026-04-14 18:59:11.622932,2026-04-14 18:59:13.938144,0 days 00:00:02.315212,9,9,117,COMPLETE
33,33,0.851524,2026-04-14 18:57:54.938954,2026-04-14 18:57:57.315761,0 days 00:00:02.376807,8,9,131,COMPLETE
66,66,0.851524,2026-04-14 18:59:18.559978,2026-04-14 18:59:20.469467,0 days 00:00:01.909489,8,6,95,COMPLETE
42,42,0.851524,2026-04-14 18:58:20.391101,2026-04-14 18:58:23.899840,0 days 00:00:03.508739,9,9,183,COMPLETE
14,14,0.851524,2026-04-14 18:57:11.093470,2026-04-14 18:57:14.254310,0 days 00:00:03.160840,8,3,169,COMPLETE
60,60,0.851283,2026-04-14 18:59:04.232232,2026-04-14 18:59:06.788388,0 days 00:00:02.556156,8,8,153,COMPLETE
97,97,0.851042,2026-04-14 19:00:59.578637,2026-04-14 19:01:03.208636,0 days 00:00:03.629999,9,8,184,COMPLETE
46,46,0.850800,2026-04-14 18:58:31.962255,2026-04-14 18:58:35.764773,0 days 00:00:03.802518,10,8,178,COMPLETE
53,53,0.850800,2026-04-14 18:58:48.799670,2026-04-14 18:58:51.890314,0 days 00:00:03.090644,9,9,162,COMPLETE
20,20,0.850800,2026-04-14 18:57:29.236173,2026-04-14 18:57:30.837966,0 days 00:00:01.601793,8,7,85,COMPLETE
21,21,0.850800,2026-04-14 18:57:30.839966,2026-04-14 18:57:32.443887,0 days 00:00:01.603921,8,7,82,COMPLETE
82,82,0.850799,2026-04-14 19:00:10.771558,2026-04-14 19:00:13.917555,0 days 00:00:03.145997,7,9,187,COMPLETE
69,69,0.850559,2026-04-14 18:59:24.345941,2026-04-14 18:59:28.174751,0 days 00:00:03.828810,9,5,200,COMPLETE
72,72,0.850558,2026-04-14 18:59:34.731111,2026-04-14 18:59:37.715265,0 days 00:00:02.984154,7,10,175,COMPLETE
65,65,0.850317,2026-04-14 18:59:15.561799,2026-04-14 18:59:18.558976,0 days 00:00:02.997177,10,9,139,COMPLETE
92,92,0.850317,2026-04-14 19:00:45.878641,2026-04-14 19:00:48.966132,0 days 00:00:03.087491,7,9,179,COMPLETE
99,99,0.850317,2026-04-14 19:01:06.887280,2026-04-14 19:01:09.639234,0 days 00:00:02.751954,7,9,166,COMPLETE
79,79,0.850317,2026-04-14 19:00:01.480855,2026-04-14 19:00:05.324731,0 days 00:00:03.843876,10,10,181,COMPLETE
75,75,0.850317,2026-04-14 18:59:45.889757,2026-04-14 18:59:49.570345,0 days 00:00:03.680588,10,10,169,COMPLETE
19,19,0.850317,2026-04-14 18:57:26.541994,2026-04-14 18:57:29.234174,0 days 00:00:02.692180,7,7,173,COMPLETE
86,86,0.850316,2026-04-14 19:00:25.593371,2026-04-14 19:00:28.768520,0 days 00:00:03.175149,7,10,189,COMPLETE
96,96,0.850076,2026-04-14 19:00:55.805060,2026-04-14 19:00:59.577617,0 days 00:00:03.772557,10,9,175,COMPLETE
22,22,0.850076,2026-04-14 18:57:32.445890,2026-04-14 18:57:34.222518,0 days 00:00:01.776628,9,8,78,COMPLETE
57,57,0.850075,2026-04-14 18:58:57.321385,2026-04-14 18:59:01.298467,0 days 00:00:03.977082,10,6,193,COMPLETE
16,16,0.850075,2026-04-14 18:57:16.385087,2026-04-14 18:57:19.249920,0 days 00:00:02.864833,7,3,172,COMPLETE
67,67,0.849834,2026-04-14 18:59:20.470476,2026-04-14 18:59:22.347505,0 days 00:00:01.877029,7,7,112,COMPLETE
62,62,0.849834,2026-04-14 18:59:09.347764,2026-04-14 18:59:11.621932,0 days 00:00:02.274168,7,9,125,COMPLETE
56,56,0.849593,2026-04-14 18:58:55.462718,2026-04-14 18:58:57.320386,0 days 00:00:01.857668,7,5,111,COMPLETE
17,17,0.849592,2026-04-14 18:57:19.250916,2026-04-14 18:57:21.934115,0 days 00:00:02.683199,7,4,165,COMPLETE
50,50,0.849351,2026-04-14 18:58:41.258701,2026-04-14 18:58:43.726050,0 days 00:00:02.467349,7,6,145,COMPLETE
12,12,0.849110,2026-04-14 18:57:03.021667,2026-04-14 18:57:06.812883,0 days 00:00:03.791216,10,2,193,COMPLETE
13,13,0.848626,2026-04-14 18:57:06.813885,2026-04-14 18:57:11.092471,0 days 00:00:04.278586,10,2,200,COMPLETE
80,80,0.848385,2026-04-14 19:00:05.325734,2026-04-14 19:00:07.656425,0 days 00:00:02.330691,6,10,164,COMPLETE
25,25,0.847661,2026-04-14 18:57:37.674785,2026-04-14 18:57:38.786525,0 days 00:00:01.111740,9,7,46,COMPLETE
36,36,0.847419,2026-04-14 18:58:03.340135,2026-04-14 18:58:06.267069,0 days 00:00:02.926934,11,8,127,COMPLETE
73,73,0.847179,2026-04-14 18:59:37.716266,2026-04-14 18:59:42.304493,0 days 00:00:04.588227,11,10,187,COMPLETE
43,43,0.847178,2026-04-14 18:58:23.903013,2026-04-14 18:58:26.587350,0 days 00:00:02.684337,6,9,184,COMPLETE
52,52,0.846937,2026-04-14 18:58:46.058056,2026-04-14 18:58:48.797670,0 days 00:00:02.739614,11,10,117,COMPLETE
84,84,0.846696,2026-04-14 19:00:17.378638,2026-04-14 19:00:21.817474,0 days 00:00:04.438836,11,10,198,COMPLETE
89,89,0.846695,2026-04-14 19:00:36.745173,2026-04-14 19:00:39.146655,0 days 00:00:02.401482,6,10,161,COMPLETE
34,34,0.846454,2026-04-14 18:57:57.317762,2026-04-14 18:57:59.453814,0 days 00:00:02.136052,6,10,149,COMPLETE
32,32,0.846212,2026-04-14 18:57:53.223629,2026-04-14 18:57:54.937776,0 days 00:00:01.714147,6,6,109,COMPLETE
11,11,0.845972,2026-04-14 18:56:58.531485,2026-04-14 18:57:03.020665,0 days 00:00:04.489180,11,2,190,COMPLETE
64,64,0.845729,2026-04-14 18:59:13.939138,2026-04-14 18:59:15.560798,0 days 00:00:01.621660,6,10,104,COMPLETE
54,54,0.844764,2026-04-14 18:58:51.891318,2026-04-14 18:58:53.354902,0 days 00:00:01.463584,6,8,97,COMPLETE
15,15,0.844763,2026-04-14 18:57:14.255309,2026-04-14 18:57:16.383056,0 days 00:00:02.127747,6,3,158,COMPLETE
68,68,0.844280,2026-04-14 18:59:22.348505,2026-04-14 18:59:24.344941,0 days 00:00:01.996436,6,8,126,COMPLETE
87,87,0.843316,2026-04-14 19:00:28.769520,2026-04-14 19:00:32.964791,0 days 00:00:04.195271,12,9,175,COMPLETE
44,44,0.842592,2026-04-14 18:58:26.590354,2026-04-14 18:58:30.165027,0 days 00:00:03.574673,12,10,156,COMPLETE
59,59,0.841868,2026-04-14 18:59:02.010917,2026-04-14 18:59:04.229227,0 days 00:00:02.218310,12,8,89,COMPLETE
10,10,0.841385,2026-04-14 18:56:53.864463,2026-04-14 18:56:58.530484,0 days 00:00:04.666021,12,2,197,COMPLETE
94,94,0.841142,2026-04-14 19:00:50.175759,2026-04-14 19:00:52.604822,0 days 00:00:02.429063,5,9,189,COMPLETE
48,48,0.840660,2026-04-14 18:58:37.913393,2026-04-14 18:58:40.029975,0 days 00:00:02.116582,13,10,70,COMPLETE
77,77,0.840177,2026-04-14 18:59:53.096867,2026-04-14 18:59:57.627821,0 days 00:00:04.530954,13,10,178,COMPLETE
7,7,0.838970,2026-04-14 18:56:48.500443,2026-04-14 18:56:52.023361,0 days 00:00:03.522918,13,6,141,COMPLETE
27,27,0.834865,2026-04-14 18:57:40.157844,2026-04-14 18:57:43.503268,0 days 00:00:03.345424,14,7,119,COMPLETE
35,35,0.833416,2026-04-14 18:57:59.455813,2026-04-14 18:58:03.339133,0 days 00:00:03.883320,15,9,133,COMPLETE
23,23,0.828830,2026-04-14 18:57:34.223518,2026-04-14 18:57:36.694800,0 days 00:00:02.471282,16,10,80,COMPLETE
45,45,0.827141,2026-04-14 18:58:30.167030,2026-04-14 18:58:31.961256,0 days 00:00:01.794226,5,9,127,COMPLETE
5,5,0.826912,2026-04-14 18:56:46.727921,2026-04-14 18:56:47.138159,0 days 00:00:00.410238,3,9,11,COMPLETE
2,2,0.818209,2026-04-14 18:56:40.723514,2026-04-14 18:56:43.120176,0 days 00:00:02.396662,5,8,72,COMPLETE
26,26,0.817967,2026-04-14 18:57:38.787525,2026-04-14 18:57:40.157844,0 days 00:00:01.370319,5,8,90,COMPLETE
39,39,0.817726,2026-04-14 18:58:12.690009,2026-04-14 18:58:13.878567,0 days 00:00:01.188558,4,6,101,COMPLETE
24,24,0.816520,2026-04-14 18:57:36.696799,2026-04-14 18:57:37.673774,0 days 00:00:00.976975,5,7,62,COMPLETE
30,30,0.816037,2026-04-14 18:57:50.205960,2026-04-14 18:57:51.253054,0 days 00:00:01.047094,4,5,95,COMPLETE
6,6,0.814586,2026-04-14 18:56:47.139164,2026-04-14 18:56:48.500443,0 days 00:00:01.361279,4,5,119,COMPLETE
49,49,0.813139,2026-04-14 18:58:40.030976,2026-04-14 18:58:41.256703,0 days 00:00:01.225727,4,10,107,COMPLETE
3,3,0.810724,2026-04-14 18:56:43.121177,2026-04-14 18:56:45.437946,0 days 00:00:02.316769,3,5,103,COMPLETE
1,1,0.810724,2026-04-14 18:56:38.150179,2026-04-14 18:56:40.722515,0 days 00:00:02.572336,2,9,166,COMPLETE
93,93,0.810482,2026-04-14 19:00:48.968129,2026-04-14 19:00:50.174759,0 days 00:00:01.206630,2,9,169,COMPLETE
37,37,0.808793,2026-04-14 18:58:06.268070,2026-04-14 18:58:07.188213,0 days 00:00:00.920143,2,5,109,COMPLETE
4,4,0.808551,2026-04-14 18:56:45.438951,2026-04-14 18:56:46.726921,0 days 00:00:01.287970,3,5,137,COMPLETE
8,8,0.807587,2026-04-14 18:56:52.023361,2026-04-14 18:56:52.693011,0 days 00:00:00.669650,3,6,54,COMPLETE
58,58,0.805898,2026-04-14 18:59:01.299466,2026-04-14 18:59:02.009919,0 days 00:00:00.710453,5,10,34,COMPLETE
18,18,0.804930,2026-04-14 18:57:21.935115,2026-04-14 18:57:26.540995,0 days 00:00:04.605880,18,3,140,COMPLETE
0,0,0.787549,2026-04-14 18:56:32.742447,2026-04-14 18:56:38.149178,0 days 00:00:05.406731,20,4,99,COMPLETE
29,29,0.746266,2026-04-14 18:57:45.717502,2026-04-14 18:57:50.203960,0 days 00:00:04.486458,24,4,119,COMPLETE
9,9,0.737089,2026-04-14 18:56:52.693011,2026-04-14 18:56:53.863460,0 days 00:00:01.170449,26,6,27,COMPLETE
38,38,0.673352,2026-04-14 18:58:07.189212,2026-04-14 18:58:12.689010,0 days 00:00:05.499798,32,4,149,COMPLETE

In [46]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_unscaled_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_unscaled_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_unscaled_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=8,
                       min_samples_split=9, n_estimators=184, random_state=42)

In [47]:
y_pred = model.predict(X_test)

In [48]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96     10355
           1       0.54      0.84      0.66      1035

    accuracy                           0.92     11390
   macro avg       0.76      0.88      0.81     11390
weighted avg       0.94      0.92      0.93     11390

In [49]:
recall_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### No scaling, f1 as eval metric

In [50]:
# Parameter tuning
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score


def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring="f1",
        n_jobs=-1,
    )
    f1 = scores.mean()
    return f1


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

f1_df = study.trials_dataframe().sort_values("value", ascending=False)
top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-04-14 19:01:12,818] A new study created in memory with name: no-name-92d17761-1650-4401-aefe-4299b0d3a93e
[I 2026-04-14 19:01:14,366] Trial 0 finished with value: 0.6640110440501512 and parameters: {'n_estimators': 143, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 0 with value: 0.6640110440501512.
[I 2026-04-14 19:01:15,058] Trial 1 finished with value: 0.6191672801548862 and parameters: {'n_estimators': 62, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 0 with value: 0.6640110440501512.
[I 2026-04-14 19:01:16,351] Trial 2 finished with value: 0.6520957929123067 and parameters: {'n_estimators': 129, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.6640110440501512.
[I 2026-04-14 19:01:17,525] Trial 3 finished with value: 0.6445321610810838 and parameters: {'n_estimators': 130, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 0 with value: 0.6640110440501512.
[I 2026-04-14 19:01:19,918] Trial 4 finished with value: 0.6691191968373433 and parameters: {'n_estimators': 158, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 4 with value: 0.6691191968373433.
[I 2026-04-14 19:01:20,616] Trial 5 finished with value: 0.5007559489701323 and parameters: {'n_estimators': 78, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 4 with value: 0.6691191968373433.
[I 2026-04-14 19:01:22,644] Trial 6 finished with value: 0.6885673787249038 and parameters: {'n_estimators': 65, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 6 with value: 0.6885673787249038.
[I 2026-04-14 19:01:24,069] Trial 7 finished with value: 0.6691072656995337 and parameters: {'n_estimators': 104, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 6 with value: 0.6885673787249038.
[I 2026-04-14 19:01:27,725] Trial 8 finished with value: 0.6746121094683379 and parameters: {'n_estimators': 151, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 6 with value: 0.6885673787249038.
[I 2026-04-14 19:01:29,245] Trial 9 finished with value: 0.6674107820397553 and parameters: {'n_estimators': 127, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 6 with value: 0.6885673787249038.
[I 2026-04-14 19:01:30,196] Trial 10 finished with value: 0.6502777137435756 and parameters: {'n_estimators': 19, 'max_depth': 26, 'min_samples_split': 2}. Best is trial 6 with value: 0.6885673787249038.
[I 2026-04-14 19:01:34,890] Trial 11 finished with value: 0.6915231558568056 and parameters: {'n_estimators': 187, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 11 with value: 0.6915231558568056.
[I 2026-04-14 19:01:39,938] Trial 12 finished with value: 0.6924457813760914 and parameters: {'n_estimators': 191, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 12 with value: 0.6924457813760914.
[I 2026-04-14 19:01:46,625] Trial 13 finished with value: 0.697019562716209 and parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 13 with value: 0.697019562716209.
[I 2026-04-14 19:01:54,153] Trial 14 finished with value: 0.6295024663780718 and parameters: {'n_estimators': 197, 'max_depth': 29, 'min_samples_split': 2}. Best is trial 13 with value: 0.697019562716209.
[I 2026-04-14 19:01:59,983] Trial 15 finished with value: 0.6846182810086618 and parameters: {'n_estimators': 176, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 13 with value: 0.697019562716209.
[I 2026-04-14 19:02:03,285] Trial 16 finished with value: 0.6681414535386985 and parameters: {'n_estimators': 174, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 13 with value: 0.697019562716209.
[I 2026-04-14 19:02:09,536] Trial 17 finished with value: 0.6971369197098383 and parameters: {'n_estimators': 199, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:14,826] Trial 18 finished with value: 0.6965709461494061 and parameters: {'n_estimators': 165, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:20,749] Trial 19 finished with value: 0.6965631841455746 and parameters: {'n_estimators': 200, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:22,464] Trial 20 finished with value: 0.6679626029884786 and parameters: {'n_estimators': 102, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:27,704] Trial 21 finished with value: 0.6970366493791107 and parameters: {'n_estimators': 168, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:34,785] Trial 22 finished with value: 0.6285604869780961 and parameters: {'n_estimators': 188, 'max_depth': 31, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:40,355] Trial 23 finished with value: 0.6915136256692647 and parameters: {'n_estimators': 175, 'max_depth': 20, 'min_samples_split': 5}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:43,671] Trial 24 finished with value: 0.668330464015002 and parameters: {'n_estimators': 165, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:47,949] Trial 25 finished with value: 0.6967203577058554 and parameters: {'n_estimators': 143, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:54,588] Trial 26 finished with value: 0.671247356004785 and parameters: {'n_estimators': 182, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:58,643] Trial 27 finished with value: 0.6693310059305284 and parameters: {'n_estimators': 198, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:02:59,471] Trial 28 finished with value: 0.6949773831276055 and parameters: {'n_estimators': 24, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:03:01,774] Trial 29 finished with value: 0.6685470965295277 and parameters: {'n_estimators': 146, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:03:06,128] Trial 30 finished with value: 0.6736524340623122 and parameters: {'n_estimators': 118, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 17 with value: 0.6971369197098383.
[I 2026-04-14 19:03:11,205] Trial 31 finished with value: 0.697157103550764 and parameters: {'n_estimators': 163, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:16,492] Trial 32 finished with value: 0.6931359988201563 and parameters: {'n_estimators': 167, 'max_depth': 18, 'min_samples_split': 10}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:20,130] Trial 33 finished with value: 0.6852231497777662 and parameters: {'n_estimators': 156, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:26,836] Trial 34 finished with value: 0.6243390084928653 and parameters: {'n_estimators': 180, 'max_depth': 32, 'min_samples_split': 3}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:30,982] Trial 35 finished with value: 0.6956917842819983 and parameters: {'n_estimators': 137, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:37,369] Trial 36 finished with value: 0.6912170113436652 and parameters: {'n_estimators': 188, 'max_depth': 21, 'min_samples_split': 9}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:38,752] Trial 37 finished with value: 0.6532504353520159 and parameters: {'n_estimators': 34, 'max_depth': 26, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:42,274] Trial 38 finished with value: 0.6917809948216592 and parameters: {'n_estimators': 117, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:43,875] Trial 39 finished with value: 0.6508792252272385 and parameters: {'n_estimators': 159, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:47,654] Trial 40 finished with value: 0.6746501209731501 and parameters: {'n_estimators': 171, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:51,681] Trial 41 finished with value: 0.6966471632983319 and parameters: {'n_estimators': 140, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:03:56,308] Trial 42 finished with value: 0.6970232762705116 and parameters: {'n_estimators': 151, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:01,751] Trial 43 finished with value: 0.6844391844570679 and parameters: {'n_estimators': 158, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:07,218] Trial 44 finished with value: 0.644342304648821 and parameters: {'n_estimators': 150, 'max_depth': 27, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:09,698] Trial 45 finished with value: 0.6855865912836782 and parameters: {'n_estimators': 95, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:13,438] Trial 46 finished with value: 0.6687141326779245 and parameters: {'n_estimators': 192, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:17,183] Trial 47 finished with value: 0.6941357427892358 and parameters: {'n_estimators': 132, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:18,565] Trial 48 finished with value: 0.6438916379429932 and parameters: {'n_estimators': 181, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:22,643] Trial 49 finished with value: 0.692578342430582 and parameters: {'n_estimators': 122, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:24,946] Trial 50 finished with value: 0.6899174777067806 and parameters: {'n_estimators': 81, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 31 with value: 0.697157103550764.
[I 2026-04-14 19:04:29,402] Trial 51 finished with value: 0.6992669209474749 and parameters: {'n_estimators': 146, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:34,309] Trial 52 finished with value: 0.698612838902388 and parameters: {'n_estimators': 155, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:38,971] Trial 53 finished with value: 0.6989830182006231 and parameters: {'n_estimators': 150, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:43,985] Trial 54 finished with value: 0.6971875911540398 and parameters: {'n_estimators': 162, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:48,490] Trial 55 finished with value: 0.6749433293587296 and parameters: {'n_estimators': 134, 'max_depth': 23, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:50,485] Trial 56 finished with value: 0.6687479189606221 and parameters: {'n_estimators': 160, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:53,974] Trial 57 finished with value: 0.6930808752657871 and parameters: {'n_estimators': 126, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:04:57,391] Trial 58 finished with value: 0.6752254674290895 and parameters: {'n_estimators': 149, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:01,473] Trial 59 finished with value: 0.6368759782064053 and parameters: {'n_estimators': 113, 'max_depth': 28, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:06,340] Trial 60 finished with value: 0.6974357241502169 and parameters: {'n_estimators': 163, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:11,212] Trial 61 finished with value: 0.6967513546109805 and parameters: {'n_estimators': 164, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:15,704] Trial 62 finished with value: 0.6988037352234584 and parameters: {'n_estimators': 142, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:20,832] Trial 63 finished with value: 0.6857797352863828 and parameters: {'n_estimators': 154, 'max_depth': 21, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:24,512] Trial 64 finished with value: 0.690882278048486 and parameters: {'n_estimators': 142, 'max_depth': 13, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:29,868] Trial 65 finished with value: 0.6977294933131774 and parameters: {'n_estimators': 173, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:36,211] Trial 66 finished with value: 0.6713938021888964 and parameters: {'n_estimators': 178, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:38,820] Trial 67 finished with value: 0.6677412347374828 and parameters: {'n_estimators': 145, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:44,251] Trial 68 finished with value: 0.6941051169535544 and parameters: {'n_estimators': 174, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:47,900] Trial 69 finished with value: 0.6956336825395684 and parameters: {'n_estimators': 128, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:53,313] Trial 70 finished with value: 0.6969453922504398 and parameters: {'n_estimators': 170, 'max_depth': 19, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:05:58,170] Trial 71 finished with value: 0.6984762601896461 and parameters: {'n_estimators': 162, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:06:02,706] Trial 72 finished with value: 0.6990515075608567 and parameters: {'n_estimators': 157, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:06:07,854] Trial 73 finished with value: 0.6856108600182133 and parameters: {'n_estimators': 155, 'max_depth': 21, 'min_samples_split': 2}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:06:11,481] Trial 74 finished with value: 0.6859507101675651 and parameters: {'n_estimators': 148, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 51 with value: 0.6992669209474749.
[I 2026-04-14 19:06:15,411] Trial 75 finished with value: 0.6993921171707748 and parameters: {'n_estimators': 137, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:19,340] Trial 76 finished with value: 0.695109474240226 and parameters: {'n_estimators': 139, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:23,814] Trial 77 finished with value: 0.651001509086525 and parameters: {'n_estimators': 133, 'max_depth': 26, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:27,114] Trial 78 finished with value: 0.6972781233491637 and parameters: {'n_estimators': 110, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:30,315] Trial 79 finished with value: 0.6693265684474182 and parameters: {'n_estimators': 152, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:34,137] Trial 80 finished with value: 0.6905986155808503 and parameters: {'n_estimators': 143, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:39,617] Trial 81 finished with value: 0.6927466975890486 and parameters: {'n_estimators': 159, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:44,937] Trial 82 finished with value: 0.6982808559578719 and parameters: {'n_estimators': 171, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:49,972] Trial 83 finished with value: 0.6972510061846163 and parameters: {'n_estimators': 171, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:54,696] Trial 84 finished with value: 0.6747062393907866 and parameters: {'n_estimators': 136, 'max_depth': 23, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:06:58,993] Trial 85 finished with value: 0.692802026198364 and parameters: {'n_estimators': 167, 'max_depth': 14, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:04,568] Trial 86 finished with value: 0.6970256269486514 and parameters: {'n_estimators': 184, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:10,412] Trial 87 finished with value: 0.6946227628037384 and parameters: {'n_estimators': 175, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:12,162] Trial 88 finished with value: 0.657531908910899 and parameters: {'n_estimators': 155, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:16,936] Trial 89 finished with value: 0.6840661810537829 and parameters: {'n_estimators': 192, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:19,081] Trial 90 finished with value: 0.6581741530771633 and parameters: {'n_estimators': 55, 'max_depth': 25, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:24,324] Trial 91 finished with value: 0.6974357241502169 and parameters: {'n_estimators': 163, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:29,209] Trial 92 finished with value: 0.6803814647750936 and parameters: {'n_estimators': 148, 'max_depth': 22, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:34,479] Trial 93 finished with value: 0.6968087996643317 and parameters: {'n_estimators': 158, 'max_depth': 19, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:39,307] Trial 94 finished with value: 0.6953255523957372 and parameters: {'n_estimators': 168, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 75 with value: 0.6993921171707748.
[I 2026-04-14 19:07:43,386] Trial 95 finished with value: 0.6966471632983319 and parameters: {'n_estimators': 140, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 75 with value: 0.6993921171707748.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
75,75,0.699392,2026-04-14 19:06:11.483062,2026-04-14 19:06:15.411720,0 days 00:00:03.928658,17,2,137,COMPLETE
51,51,0.699267,2026-04-14 19:04:24.947529,2026-04-14 19:04:29.401116,0 days 00:00:04.453587,17,2,146,COMPLETE
72,72,0.699052,2026-04-14 19:05:58.171563,2026-04-14 19:06:02.705274,0 days 00:00:04.533711,17,2,157,COMPLETE
53,53,0.698983,2026-04-14 19:04:34.310195,2026-04-14 19:04:38.971535,0 days 00:00:04.661340,17,2,150,COMPLETE
62,62,0.698804,2026-04-14 19:05:11.213238,2026-04-14 19:05:15.704903,0 days 00:00:04.491665,18,2,142,COMPLETE

In [60]:
f1_df

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
75,75,0.699392,2026-04-14 19:06:11.483062,2026-04-14 19:06:15.411720,0 days 00:00:03.928658,17,2,137,COMPLETE
51,51,0.699267,2026-04-14 19:04:24.947529,2026-04-14 19:04:29.401116,0 days 00:00:04.453587,17,2,146,COMPLETE
72,72,0.699052,2026-04-14 19:05:58.171563,2026-04-14 19:06:02.705274,0 days 00:00:04.533711,17,2,157,COMPLETE
53,53,0.698983,2026-04-14 19:04:34.310195,2026-04-14 19:04:38.971535,0 days 00:00:04.661340,17,2,150,COMPLETE
62,62,0.698804,2026-04-14 19:05:11.213238,2026-04-14 19:05:15.704903,0 days 00:00:04.491665,18,2,142,COMPLETE
52,52,0.698613,2026-04-14 19:04:29.402113,2026-04-14 19:04:34.309194,0 days 00:00:04.907081,17,2,155,COMPLETE
71,71,0.698476,2026-04-14 19:05:53.314882,2026-04-14 19:05:58.169563,0 days 00:00:04.854681,17,2,162,COMPLETE
82,82,0.698281,2026-04-14 19:06:39.618725,2026-04-14 19:06:44.937835,0 days 00:00:05.319110,17,2,171,COMPLETE
65,65,0.697729,2026-04-14 19:05:24.513892,2026-04-14 19:05:29.868677,0 days 00:00:05.354785,18,2,173,COMPLETE
60,60,0.697436,2026-04-14 19:05:01.474925,2026-04-14 19:05:06.340623,0 days 00:00:04.865698,18,3,163,COMPLETE
91,91,0.697436,2026-04-14 19:07:19.082462,2026-04-14 19:07:24.324521,0 days 00:00:05.242059,18,3,163,COMPLETE
78,78,0.697278,2026-04-14 19:06:23.815587,2026-04-14 19:06:27.113434,0 days 00:00:03.297847,17,2,110,COMPLETE
83,83,0.697251,2026-04-14 19:06:44.939838,2026-04-14 19:06:49.972709,0 days 00:00:05.032871,16,2,171,COMPLETE
54,54,0.697188,2026-04-14 19:04:38.972538,2026-04-14 19:04:43.985380,0 days 00:00:05.012842,18,2,162,COMPLETE
31,31,0.697157,2026-04-14 19:03:06.129038,2026-04-14 19:03:11.205673,0 days 00:00:05.076635,16,2,163,COMPLETE
17,17,0.697137,2026-04-14 19:02:03.286913,2026-04-14 19:02:09.536992,0 days 00:00:06.250079,19,3,199,COMPLETE
21,21,0.697037,2026-04-14 19:02:22.466805,2026-04-14 19:02:27.704737,0 days 00:00:05.237932,19,3,168,COMPLETE
86,86,0.697026,2026-04-14 19:06:58.994251,2026-04-14 19:07:04.568650,0 days 00:00:05.574399,17,3,184,COMPLETE
42,42,0.697023,2026-04-14 19:03:51.682445,2026-04-14 19:03:56.308624,0 days 00:00:04.626179,16,2,151,COMPLETE
13,13,0.697020,2026-04-14 19:01:39.939939,2026-04-14 19:01:46.625188,0 days 00:00:06.685249,19,3,200,COMPLETE
70,70,0.696945,2026-04-14 19:05:47.900689,2026-04-14 19:05:53.313881,0 days 00:00:05.413192,19,2,170,COMPLETE
93,93,0.696809,2026-04-14 19:07:29.211926,2026-04-14 19:07:34.479734,0 days 00:00:05.267808,19,2,158,COMPLETE
61,61,0.696751,2026-04-14 19:05:06.341626,2026-04-14 19:05:11.212237,0 days 00:00:04.870611,17,3,164,COMPLETE
99,99,0.696741,2026-04-14 19:07:58.763499,2026-04-14 19:08:03.961495,0 days 00:00:05.197996,19,4,163,COMPLETE
25,25,0.696720,2026-04-14 19:02:43.672381,2026-04-14 19:02:47.949590,0 days 00:00:04.277209,16,2,143,COMPLETE
95,95,0.696647,2026-04-14 19:07:39.308128,2026-04-14 19:07:43.386259,0 days 00:00:04.078131,16,2,140,COMPLETE
41,41,0.696647,2026-04-14 19:03:47.655077,2026-04-14 19:03:51.681335,0 days 00:00:04.026258,16,2,140,COMPLETE
18,18,0.696571,2026-04-14 19:02:09.537993,2026-04-14 19:02:14.826279,0 days 00:00:05.288286,19,3,165,COMPLETE
19,19,0.696563,2026-04-14 19:02:14.827280,2026-04-14 19:02:20.748588,0 days 00:00:05.921308,18,5,200,COMPLETE
35,35,0.695692,2026-04-14 19:03:26.837392,2026-04-14 19:03:30.982238,0 days 00:00:04.144846,17,4,137,COMPLETE
69,69,0.695634,2026-04-14 19:05:44.252186,2026-04-14 19:05:47.899687,0 days 00:00:03.647501,15,3,128,COMPLETE
94,94,0.695326,2026-04-14 19:07:34.481730,2026-04-14 19:07:39.307127,0 days 00:00:04.825397,15,3,168,COMPLETE
96,96,0.695221,2026-04-14 19:07:43.387259,2026-04-14 19:07:48.673021,0 days 00:00:05.285762,17,6,184,COMPLETE
76,76,0.695109,2026-04-14 19:06:15.412723,2026-04-14 19:06:19.340014,0 days 00:00:03.927291,15,2,139,COMPLETE
28,28,0.694977,2026-04-14 19:02:58.644905,2026-04-14 19:02:59.471092,0 days 00:00:00.826187,15,4,24,COMPLETE
87,87,0.694623,2026-04-14 19:07:04.569651,2026-04-14 19:07:10.412332,0 days 00:00:05.842681,20,2,175,COMPLETE
47,47,0.694136,2026-04-14 19:04:13.438615,2026-04-14 19:04:17.183071,0 days 00:00:03.744456,15,8,132,COMPLETE
68,68,0.694105,2026-04-14 19:05:38.821896,2026-04-14 19:05:44.251179,0 days 00:00:05.429283,18,7,174,COMPLETE
32,32,0.693136,2026-04-14 19:03:11.206672,2026-04-14 19:03:16.492110,0 days 00:00:05.285438,18,10,167,COMPLETE
57,57,0.693081,2026-04-14 19:04:50.486581,2026-04-14 19:04:53.974844,0 days 00:00:03.488263,14,2,126,COMPLETE
85,85,0.692802,2026-04-14 19:06:54.698655,2026-04-14 19:06:58.993249,0 days 00:00:04.294594,14,2,167,COMPLETE
81,81,0.692747,2026-04-14 19:06:34.139332,2026-04-14 19:06:39.617722,0 days 00:00:05.478390,20,3,159,COMPLETE
49,49,0.692578,2026-04-14 19:04:18.566412,2026-04-14 19:04:22.643089,0 days 00:00:04.076677,20,3,122,COMPLETE
12,12,0.692446,2026-04-14 19:01:34.891359,2026-04-14 19:01:39.938940,0 days 00:00:05.047581,14,3,191,COMPLETE
38,38,0.691781,2026-04-14 19:03:38.753729,2026-04-14 19:03:42.274267,0 days 00:00:03.520538,14,4,117,COMPLETE
11,11,0.691523,2026-04-14 19:01:30.198779,2026-04-14 19:01:34.890359,0 days 00:00:04.691580,13,4,187,COMPLETE
23,23,0.691514,2026-04-14 19:02:34.786699,2026-04-14 19:02:40.355508,0 days 00:00:05.568809,20,5,175,COMPLETE
36,36,0.691217,2026-04-14 19:03:30.983239,2026-04-14 19:03:37.369790,0 days 00:00:06.386551,21,9,188,COMPLETE
64,64,0.690882,2026-04-14 19:05:20.833167,2026-04-14 19:05:24.512891,0 days 00:00:03.679724,13,2,142,COMPLETE
80,80,0.690599,2026-04-14 19:06:30.316185,2026-04-14 19:06:34.137328,0 days 00:00:03.821143,14,9,143,COMPLETE
97,97,0.690474,2026-04-14 19:07:48.675020,2026-04-14 19:07:52.397325,0 days 00:00:03.722305,13,2,152,COMPLETE
50,50,0.689917,2026-04-14 19:04:22.644091,2026-04-14 19:04:24.946506,0 days 00:00:02.302415,13,5,81,COMPLETE
6,6,0.688567,2026-04-14 19:01:20.617953,2026-04-14 19:01:22.644938,0 days 00:00:02.026985,13,7,65,COMPLETE
74,74,0.685951,2026-04-14 19:06:07.855953,2026-04-14 19:06:11.481063,0 days 00:00:03.625110,12,3,148,COMPLETE
63,63,0.685780,2026-04-14 19:05:15.705902,2026-04-14 19:05:20.832167,0 days 00:00:05.126265,21,2,154,COMPLETE
73,73,0.685611,2026-04-14 19:06:02.707269,2026-04-14 19:06:07.853952,0 days 00:00:05.146683,21,2,155,COMPLETE
45,45,0.685587,2026-04-14 19:04:07.219742,2026-04-14 19:04:09.698895,0 days 00:00:02.479153,12,2,95,COMPLETE
33,33,0.685223,2026-04-14 19:03:16.493107,2026-04-14 19:03:20.129782,0 days 00:00:03.636675,12,2,156,COMPLETE
15,15,0.684618,2026-04-14 19:01:54.155730,2026-04-14 19:01:59.983866,0 days 00:00:05.828136,22,3,176,COMPLETE
43,43,0.684439,2026-04-14 19:03:56.309624,2026-04-14 19:04:01.751052,0 days 00:00:05.441428,22,3,158,COMPLETE
89,89,0.684066,2026-04-14 19:07:12.164341,2026-04-14 19:07:16.936292,0 days 00:00:04.771951,12,2,192,COMPLETE
92,92,0.680381,2026-04-14 19:07:24.325521,2026-04-14 19:07:29.209924,0 days 00:00:04.884403,22,2,148,COMPLETE
58,58,0.675225,2026-04-14 19:04:53.974844,2026-04-14 19:04:57.391459,0 days 00:00:03.416615,11,2,149,COMPLETE
55,55,0.674943,2026-04-14 19:04:43.986402,2026-04-14 19:04:48.490037,0 days 00:00:04.503635,23,2,134,COMPLETE
84,84,0.674706,2026-04-14 19:06:49.973708,2026-04-14 19:06:54.696662,0 days 00:00:04.722954,23,2,136,COMPLETE
40,40,0.674650,2026-04-14 19:03:43.876332,2026-04-14 19:03:47.654077,0 days 00:00:03.777745,11,6,171,COMPLETE
8,8,0.674612,2026-04-14 19:01:24.071314,2026-04-14 19:01:27.725953,0 days 00:00:03.654639,11,5,151,COMPLETE
30,30,0.673652,2026-04-14 19:03:01.775864,2026-04-14 19:03:06.128037,0 days 00:00:04.352173,24,3,118,COMPLETE
66,66,0.671394,2026-04-14 19:05:29.869678,2026-04-14 19:05:36.211151,0 days 00:00:06.341473,24,3,178,COMPLETE
26,26,0.671247,2026-04-14 19:02:47.950590,2026-04-14 19:02:54.588191,0 days 00:00:06.637601,24,3,182,COMPLETE
27,27,0.669331,2026-04-14 19:02:54.589188,2026-04-14 19:02:58.643904,0 days 00:00:04.054716,10,5,198,COMPLETE
79,79,0.669327,2026-04-14 19:06:27.116437,2026-04-14 19:06:30.315182,0 days 00:00:03.198745,10,2,152,COMPLETE
4,4,0.669119,2026-04-14 19:01:17.526992,2026-04-14 19:01:19.918655,0 days 00:00:02.391663,6,6,158,COMPLETE
7,7,0.669107,2026-04-14 19:01:22.646938,2026-04-14 19:01:24.069312,0 days 00:00:01.422374,5,6,104,COMPLETE
56,56,0.668748,2026-04-14 19:04:48.491131,2026-04-14 19:04:50.485581,0 days 00:00:01.994450,5,2,160,COMPLETE
46,46,0.668714,2026-04-14 19:04:09.699895,2026-04-14 19:04:13.438615,0 days 00:00:03.738720,9,3,192,COMPLETE
29,29,0.668547,2026-04-14 19:02:59.474104,2026-04-14 19:03:01.774863,0 days 00:00:02.300759,7,2,146,COMPLETE
24,24,0.668330,2026-04-14 19:02:40.356509,2026-04-14 19:02:43.671379,0 days 00:00:03.314870,9,4,165,COMPLETE
16,16,0.668141,2026-04-14 19:01:59.985868,2026-04-14 19:02:03.285907,0 days 00:00:03.300039,9,4,174,COMPLETE
20,20,0.667963,2026-04-14 19:02:20.750588,2026-04-14 19:02:22.464812,0 days 00:00:01.714224,7,2,102,COMPLETE
67,67,0.667741,2026-04-14 19:05:36.212149,2026-04-14 19:05:38.820893,0 days 00:00:02.608744,8,2,145,COMPLETE
9,9,0.667411,2026-04-14 19:01:27.726952,2026-04-14 19:01:29.245226,0 days 00:00:01.518274,4,7,127,COMPLETE
0,0,0.664011,2026-04-14 19:01:12.819368,2026-04-14 19:01:14.366519,0 days 00:00:01.547151,4,10,143,COMPLETE
90,90,0.658174,2026-04-14 19:07:16.936292,2026-04-14 19:07:19.081467,0 days 00:00:02.145175,25,2,55,COMPLETE
88,88,0.657532,2026-04-14 19:07:10.413334,2026-04-14 19:07:12.162340,0 days 00:00:01.749006,4,3,155,COMPLETE
37,37,0.653250,2026-04-14 19:03:37.370797,2026-04-14 19:03:38.752727,0 days 00:00:01.381930,26,2,34,COMPLETE
2,2,0.652096,2026-04-14 19:01:15.059373,2026-04-14 19:01:16.351010,0 days 00:00:01.291637,3,4,129,COMPLETE
77,77,0.651002,2026-04-14 19:06:19.341020,2026-04-14 19:06:23.814588,0 days 00:00:04.473568,26,2,133,COMPLETE
39,39,0.650879,2026-04-14 19:03:42.275266,2026-04-14 19:03:43.875330,0 days 00:00:01.600064,3,3,159,COMPLETE
10,10,0.650278,2026-04-14 19:01:29.247222,2026-04-14 19:01:30.196780,0 days 00:00:00.949558,26,2,19,COMPLETE
3,3,0.644532,2026-04-14 19:01:16.352018,2026-04-14 19:01:17.525991,0 days 00:00:01.173973,2,9,130,COMPLETE
44,44,0.644342,2026-04-14 19:04:01.752053,2026-04-14 19:04:07.218741,0 days 00:00:05.466688,27,2,150,COMPLETE
48,48,0.643892,2026-04-14 19:04:17.184071,2026-04-14 19:04:18.565410,0 days 00:00:01.381339,2,4,181,COMPLETE
59,59,0.636876,2026-04-14 19:04:57.392460,2026-04-14 19:05:01.473922,0 days 00:00:04.081462,28,2,113,COMPLETE
14,14,0.629502,2026-04-14 19:01:46.627182,2026-04-14 19:01:54.152735,0 days 00:00:07.525553,29,2,197,COMPLETE
22,22,0.628560,2026-04-14 19:02:27.705735,2026-04-14 19:02:34.785698,0 days 00:00:07.079963,31,3,188,COMPLETE
34,34,0.624339,2026-04-14 19:03:20.131782,2026-04-14 19:03:26.836390,0 days 00:00:06.704608,32,3,180,COMPLETE
98,98,0.623176,2026-04-14 19:07:52.398325,2026-04-14 19:07:58.762499,0 days 00:00:06.364174,30,2,172,COMPLETE
1,1,0.619167,2026-04-14 19:01:14.367519,2026-04-14 19:01:15.058373,0 days 00:00:00.690854,3,8,62,COMPLETE
5,5,0.500756,2026-04-14 19:01:19.920655,2026-04-14 19:01:20.616953,0 days 00:00:00.696298,2,7,78,COMPLETE

In [51]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=17, n_estimators=137,
                       random_state=42)

In [52]:
y_pred = model.predict(X_test)

In [53]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96     10355
           1       0.60      0.79      0.69      1035

    accuracy                           0.93     11390
   macro avg       0.79      0.87      0.82     11390
weighted avg       0.94      0.93      0.94     11390

In [54]:
f1_model_report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)

### Compare Models

In [62]:
# 2. Convert and transpose
recall_report_df = pd.DataFrame(recall_model_report_df).transpose()
f1_report_df = pd.DataFrame(f1_model_report).transpose()

# 3. Combine multiple reports (e.g., adding a 'Model' column for identification)
combined_df = pd.concat([recall_report_df, f1_report_df], keys=['IBM RF optimized for Recall', 'IBM RF optimized for F1'])

In [63]:
combined_df

                                          precision    recall  f1-score  \
IBM RF optimized for Recall 0              0.983030  0.928634  0.955058
                            1              0.540423  0.839614  0.657586
                            accuracy       0.920544  0.920544  0.920544
                            macro avg      0.761726  0.884124  0.806322
                            weighted avg   0.942811  0.920544  0.928027
IBM RF optimized for F1     0              0.978766  0.948141  0.963210
                            1              0.604857  0.794203  0.686717
                            accuracy       0.934153  0.934153  0.934153
                            macro avg      0.791811  0.871172  0.824963
                            weighted avg   0.944789  0.934153  0.938085

                                               support
IBM RF optimized for Recall 0             10355.000000
                            1              1035.000000
                            accuracy          0.920544
                            macro avg     11390.000000
                            weighted avg  11390.000000
IBM RF optimized for F1     0             10355.000000
                            1              1035.000000
                            accuracy          0.934153
                            macro avg     11390.000000
                            weighted avg  11390.000000

In [57]:
model.feature_importances_

array([0.08335239, 0.08734736, 0.10743503, 0.11814191, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.000488  ,
       0.00145135, 0.00052624, 0.00057799, 0.00206075, 0.00056088,
       0.00072504, 0.00059483, 0.00486041, 0.00144581, 0.0007712 ,
       0.00073988, 0.00194187, 0.00044187, 0.00059303, 0.0004747 ,
       0.00093338, 0.00053392, 0.00063552, 0.00204793, 0.00060584,
       0.00053627, 0.00048785, 0.00307947, 0.00113683, 0.00066777,
       0.00069651, 0.00211394, 0.00045382, 0.00070261, 0.33369977,
       0.00110635, 0.01911108, 0.08707958, 0.06062897, 0.01555009,
       0.00991059, 0.02742431, 0.01632708])

In [58]:
pd.set_option('display.max_rows', None)

In [59]:
importances = model.feature_importances_
feature_names = df.drop(columns='Is Laundering').columns
feature_imp_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_df

                                      Feature  Gini Importance
94                         Payment Format_ACH         0.333700
3                             Amount_Paid_USD         0.118142
2                         Amount_Received_USD         0.107435
1                                 Amount Paid         0.087347
97                      Payment Format_Cheque         0.087080
0                             Amount Received         0.083352
98                 Payment Format_Credit Card         0.060629
101                              Account_Same         0.027424
96                        Payment Format_Cash         0.019111
102                                 Bank_Same         0.016327
99                Payment Format_Reinvestment         0.015550
100                       Payment Format_Wire         0.009911
72             Receiving Currency_Saudi Riyal         0.004860
87               Payment Currency_Saudi Riyal         0.003079
91                 Payment Currency_US Dollar         0.002114
68                    Receiving Currency_Euro         0.002061
83                      Payment Currency_Euro         0.002048
76               Receiving Currency_US Dollar         0.001942
65                 Receiving Currency_Bitcoin         0.001451
73                  Receiving Currency_Shekel         0.001446
88                    Payment Currency_Shekel         0.001137
95                     Payment Format_Bitcoin         0.001106
80                   Payment Currency_Bitcoin         0.000933
74             Receiving Currency_Swiss Franc         0.000771
75                Receiving Currency_UK Pound         0.000740
70                   Receiving Currency_Ruble         0.000725
93                      Payment Currency_Yuan         0.000703
90                  Payment Currency_UK Pound         0.000697
89               Payment Currency_Swiss Franc         0.000668
82           Payment Currency_Canadian Dollar         0.000636
84              Payment Currency_Mexican Peso         0.000606
71                   Receiving Currency_Rupee         0.000595
78                    Receiving Currency_Yuan         0.000593
67         Receiving Currency_Canadian Dollar         0.000578
69            Receiving Currency_Mexican Peso         0.000561
85                     Payment Currency_Ruble         0.000536
81               Payment Currency_Brazil Real         0.000534
66             Receiving Currency_Brazil Real         0.000526
64       Receiving Currency_Australian Dollar         0.000488
86                     Payment Currency_Rupee         0.000488
79         Payment Currency_Australian Dollar         0.000475
92                       Payment Currency_Yen         0.000454
77                     Receiving Currency_Yen         0.000442
38              UK Pound_Amount_Received_Mean         0.000000
37                UK Pound_Amount_Paid_Median         0.000000
36                  UK Pound_Amount_Paid_Mean         0.000000
31                 Yen_Amount_Received_Median         0.000000
30                   Yen_Amount_Received_Mean         0.000000
29                     Yen_Amount_Paid_Median         0.000000
28                       Yen_Amount_Paid_Mean         0.000000
27               Rupee_Amount_Received_Median         0.000000
26                 Rupee_Amount_Received_Mean         0.000000
25                   Rupee_Amount_Paid_Median         0.000000
24                     Rupee_Amount_Paid_Mean         0.000000
23                Yuan_Amount_Received_Median         0.000000
22                  Yuan_Amount_Received_Mean         0.000000
21                    Yuan_Amount_Paid_Median         0.000000
20                      Yuan_Amount_Paid_Mean         0.000000
19   Australian Dollar_Amount_Received_Median         0.000000
18     Australian Dollar_Amount_Received_Mean         0.000000
17       Australian Dollar_Amount_Paid_Median         0.000000
16         Australian Dollar_Amount_Paid_Mean         0.000000
15                Euro_Amount_Received_Median         0.000000
14                  Euro_Amount_Received_Mean         0.000000
13                    Euro_Amount_Paid_Median         0.000000
12                      Euro_Amount_Paid_Mean         0.000000
11             Bitcoin_Amount_Received_Median         0.000000
10               Bitcoin_Amount_Received_Mean         0.000000
9                  Bitcoin_Amount_Paid_Median         0.000000
8                    Bitcoin_Amount_Paid_Mean         0.000000
7            US Dollar_Amount_Received_Median         0.000000
6              US Dollar_Amount_Received_Mean         0.000000
5                US Dollar_Amount_Paid_Median         0.000000
4                  US Dollar_Amount_Paid_Mean         0.000000
35        Mexican Peso_Amount_Received_Median         0.000000
34          Mexican Peso_Amount_Received_Mean         0.000000
33            Mexican Peso_Amount_Paid_Median         0.000000
32              Mexican Peso_Amount_Paid_Mean         0.000000
63              Shekel_Amount_Received_Median         0.000000
55         Brazil Real_Amount_Received_Median         0.000000
56               Saudi Riyal_Amount_Paid_Mean         0.000000
57             Saudi Riyal_Amount_Paid_Median         0.000000
58           Saudi Riyal_Amount_Received_Mean         0.000000
59         Saudi Riyal_Amount_Received_Median         0.000000
60                    Shekel_Amount_Paid_Mean         0.000000
61                  Shekel_Amount_Paid_Median         0.000000
62                Shekel_Amount_Received_Mean         0.000000
46       Canadian Dollar_Amount_Received_Mean         0.000000
45         Canadian Dollar_Amount_Paid_Median         0.000000
44           Canadian Dollar_Amount_Paid_Mean         0.000000
43               Ruble_Amount_Received_Median         0.000000
42                 Ruble_Amount_Received_Mean         0.000000
41                   Ruble_Amount_Paid_Median         0.000000
40                     Ruble_Amount_Paid_Mean         0.000000
47     Canadian Dollar_Amount_Received_Median         0.000000
39            UK Pound_Amount_Received_Median         0.000000
48               Swiss Franc_Amount_Paid_Mean         0.000000
49             Swiss Franc_Amount_Paid_Median         0.000000
50           Swiss Franc_Amount_Received_Mean         0.000000
51         Swiss Franc_Amount_Received_Median         0.000000
52               Brazil Real_Amount_Paid_Mean         0.000000
53             Brazil Real_Amount_Paid_Median         0.000000
54           Brazil Real_Amount_Received_Mean         0.000000