In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
random_state = 42

In [3]:
df = pd.read_csv('../Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

## Baseline

In [4]:
X = df.drop(columns='Fraud')
y = df['Fraud']

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Default settings on RF

In [6]:
# Train using optimal parameters
model = RandomForestClassifier(
    random_state=random_state,
    n_jobs=-1,
)
model.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [7]:
y_pred = model.predict(X_test)

In [8]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    193688
           1       0.00      0.00      0.00        19

    accuracy                           1.00    193707
   macro avg       0.50      0.50      0.50    193707
weighted avg       1.00      1.00      1.00    193707

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [9]:
baseline_model_report_df = classification_report(y_test, y_pred, output_dict=True)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Class Weight Balanced

In [10]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    random_state=random_state,
    n_jobs=-1
)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [11]:
y_pred = model.predict(X_test)

In [12]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    193688
           1       0.00      0.00      0.00        19

    accuracy                           1.00    193707
   macro avg       0.50      0.50      0.50    193707
weighted avg       1.00      1.00      1.00    193707

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [13]:
baseline_balanced_model_report_df = classification_report(y_test, y_pred, output_dict=True)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Undersampling

In [14]:
fraud = df[df['Fraud'] == 1]
non_fraud = df[df['Fraud'] == 0]
len(fraud), len(non_fraud)

(95, 968437)

In [15]:
# Undersample majority class to a 1:10 ratio
non_fraud_downsampled = non_fraud.sample(n=len(fraud) * 10, random_state=random_state)
non_fraud_downsampled

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
495859,1.0,25.0,2.0,60,175700.0,175700.0,52.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4748.57,0,1617062400,1638835200,1641427200
751210,0.0,41.0,2.0,24,379200.0,379200.0,40.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9248.78,0,1586390400,1611619200,1613433600
302413,0.0,14.0,2.0,24,238300.0,238300.0,14.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,8510.71,0,1586217600,1605571200,1615334400
199402,0.0,8.0,2.0,24,742528.0,742528.0,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,19540.21,0,1586649600,1640044800,1642809600
52948,1.0,5.0,2.0,60,882672.0,882672.0,37.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,18389.00,0,1615593600,1640131200,1642809600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294662,0.0,13.0,2.0,24,298700.0,298700.0,13.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21335.71,0,1586908800,1630972800,1635379200
204016,0.0,9.0,2.0,24,375100.0,375100.0,42.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10717.14,0,1588032000,1623888000,1626912000
387773,0.0,20.0,2.0,24,603200.0,603200.0,20.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11827.45,0,1586044800,1627948800,1631577600
378063,0.0,19.0,2.0,24,515000.0,515000.0,37.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10510.20,0,1586995200,1614902400,1618876800
876742,0.0,47.0,2.0,24,173100.0,173100.0,46.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,4808.33,0,1588896000,1628121600,1631664000

In [16]:
# Combine and shuffle
df_reduced = pd.concat([fraud, non_fraud_downsampled]).sample(frac=1).reset_index(drop=True)
df_reduced

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,11.0,2.0,24,4840457.50,4840457.50,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11893.02,0,1586476800,1630281600,1632441600
1,1.0,23.0,2.0,60,1596546.00,1596546.00,32.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,14128.70,0,1611619200,1638748800,1642723200
2,0.0,20.0,2.0,24,186700.00,186700.00,27.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,8117.39,0,1586908800,1620259200,1622764800
3,0.0,47.0,2.0,24,297500.00,297500.00,46.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13522.73,0,1587945600,1628467200,1636761600
4,1.0,5.0,1.0,60,161091.24,161091.00,5.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,8054.45,0,1611878400,-2208988800,1611878400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,0.0,16.0,2.0,24,191000.00,191000.00,16.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9550.00,0,1586563200,1629936000,1631577600
1041,1.0,10.0,2.0,60,2000000.00,2000000.00,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10152.28,0,1616803200,1647388800,1647907200
1042,1.0,56.0,2.0,60,780000.00,780000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21081.03,0,1610755200,1638921600,1641600000
1043,1.0,45.0,2.0,60,285700.00,285700.00,44.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12986.36,0,1613520000,1635897600,1639008000
1044,1.0,38.0,2.0,60,468541.17,468541.17,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10648.55,0,1611878400,1624406400,1626825600

In [17]:
X = df_reduced.drop(columns='Fraud')
y = df_reduced['Fraud']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, 
                                                    stratify=y,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

In [19]:
cv = StratifiedKFold(n_splits=5)

### Recall as metric

In [20]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-04-14 20:46:51,815] A new study created in memory with name: no-name-73336011-1e3d-407c-b473-720802d006d4
[I 2026-04-14 20:46:53,307] Trial 0 finished with value: 0.7891666666666667 and parameters: {'n_estimators': 105, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 0 with value: 0.7891666666666667.
[I 2026-04-14 20:46:54,385] Trial 1 finished with value: 0.8025 and parameters: {'n_estimators': 48, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 1 with value: 0.8025.
[I 2026-04-14 20:46:55,467] Trial 2 finished with value: 0.8158333333333333 and parameters: {'n_estimators': 44, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 2 with value: 0.8158333333333333.
[I 2026-04-14 20:46:56,510] Trial 3 finished with value: 0.7891666666666667 and parameters: {'n_estimators': 26, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 2 with value: 0.8158333333333333.
[I 2026-04-14 20:46:56,696] Trial 4 finished with value: 0.8158333333333335 and parameters: {'n_estimators': 170, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 4 with value: 0.8158333333333335.
[I 2026-04-14 20:46:56,837] Trial 5 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 126, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 5 with value: 0.8683333333333334.
[I 2026-04-14 20:46:57,040] Trial 6 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 5 with value: 0.8683333333333334.
[I 2026-04-14 20:46:57,102] Trial 7 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 49, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 7 with value: 0.8958333333333334.
[I 2026-04-14 20:46:57,211] Trial 8 finished with value: 0.7625 and parameters: {'n_estimators': 94, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 7 with value: 0.8958333333333334.
[I 2026-04-14 20:46:57,351] Trial 9 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 149, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 7 with value: 0.8958333333333334.
[I 2026-04-14 20:46:57,429] Trial 10 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 73, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 10 with value: 0.9083333333333334.
[I 2026-04-14 20:46:57,506] Trial 11 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 72, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 10 with value: 0.9083333333333334.
[I 2026-04-14 20:46:57,583] Trial 12 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 83, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:57,679] Trial 13 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 84, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:57,818] Trial 14 finished with value: 0.8025 and parameters: {'n_estimators': 127, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:57,895] Trial 15 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 74, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:57,987] Trial 16 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 102, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,018] Trial 17 finished with value: 0.7891666666666668 and parameters: {'n_estimators': 17, 'max_depth': 31, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,159] Trial 18 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 136, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,283] Trial 19 finished with value: 0.7091666666666667 and parameters: {'n_estimators': 86, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,362] Trial 20 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 58, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,469] Trial 21 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 106, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,578] Trial 22 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 111, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,671] Trial 23 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 87, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,840] Trial 24 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 152, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:58,963] Trial 25 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 118, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,057] Trial 26 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 93, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,135] Trial 27 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 60, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,227] Trial 28 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 94, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,289] Trial 29 finished with value: 0.7625 and parameters: {'n_estimators': 33, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,367] Trial 30 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 67, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,460] Trial 31 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 104, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,554] Trial 32 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 104, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,649] Trial 33 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 81, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,757] Trial 34 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 111, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:46:59,883] Trial 35 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 141, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,007] Trial 36 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 122, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,100] Trial 37 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 103, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,164] Trial 38 finished with value: 0.8158333333333335 and parameters: {'n_estimators': 42, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,336] Trial 39 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 168, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,414] Trial 40 finished with value: 0.7758333333333333 and parameters: {'n_estimators': 61, 'max_depth': 23, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,523] Trial 41 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,616] Trial 42 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,740] Trial 43 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 131, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,833] Trial 44 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 80, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:00,941] Trial 45 finished with value: 0.8683333333333334 and parameters: {'n_estimators': 117, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,035] Trial 46 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 94, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,144] Trial 47 finished with value: 0.8550000000000001 and parameters: {'n_estimators': 108, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,235] Trial 48 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 84, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,298] Trial 49 finished with value: 0.8158333333333335 and parameters: {'n_estimators': 52, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,392] Trial 50 finished with value: 0.7625 and parameters: {'n_estimators': 69, 'max_depth': 16, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,487] Trial 51 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 88, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,565] Trial 52 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 78, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,689] Trial 53 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 122, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,782] Trial 54 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 99, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,874] Trial 55 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 87, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:01,969] Trial 56 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 91, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,082] Trial 57 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 111, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,161] Trial 58 finished with value: 0.8291666666666668 and parameters: {'n_estimators': 77, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,223] Trial 59 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 66, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,317] Trial 60 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 97, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,426] Trial 61 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 91, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,537] Trial 62 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 106, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,646] Trial 63 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 116, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,771] Trial 64 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 133, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,879] Trial 65 finished with value: 0.8025 and parameters: {'n_estimators': 83, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:02,973] Trial 66 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 98, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,051] Trial 67 finished with value: 0.9083333333333334 and parameters: {'n_estimators': 72, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,176] Trial 68 finished with value: 0.8550000000000001 and parameters: {'n_estimators': 124, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,315] Trial 69 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 142, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,395] Trial 70 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 91, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,504] Trial 71 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 103, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,676] Trial 72 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 198, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,771] Trial 73 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 96, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,882] Trial 74 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 108, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:03,960] Trial 75 finished with value: 0.8550000000000001 and parameters: {'n_estimators': 75, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,055] Trial 76 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 85, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,134] Trial 77 finished with value: 0.8550000000000001 and parameters: {'n_estimators': 65, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,211] Trial 78 finished with value: 0.7891666666666667 and parameters: {'n_estimators': 55, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,322] Trial 79 finished with value: 0.7358333333333335 and parameters: {'n_estimators': 93, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,416] Trial 80 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 102, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,526] Trial 81 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 111, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,653] Trial 82 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 118, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,731] Trial 83 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 82, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,842] Trial 84 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 106, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:04,968] Trial 85 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 128, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,077] Trial 86 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 89, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,186] Trial 87 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 114, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,281] Trial 88 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 99, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,374] Trial 89 finished with value: 0.8416666666666668 and parameters: {'n_estimators': 95, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,483] Trial 90 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 120, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,575] Trial 91 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 105, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,701] Trial 92 finished with value: 0.8158333333333335 and parameters: {'n_estimators': 109, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,779] Trial 93 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 79, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,887] Trial 94 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 101, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:05,982] Trial 95 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 87, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.
[I 2026-04-14 20:47:06,076] Trial 96 finished with value: 0.9208333333333334 and parameters: {'n_estimators': 93, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 12 with value: 0.9208333333333334.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
32,32,0.920833,2026-04-14 20:46:59.460530,2026-04-14 20:46:59.554873,0 days 00:00:00.094343,2,5,104,COMPLETE
12,12,0.920833,2026-04-14 20:46:57.506351,2026-04-14 20:46:57.583727,0 days 00:00:00.077376,2,10,83,COMPLETE
16,16,0.920833,2026-04-14 20:46:57.895209,2026-04-14 20:46:57.987623,0 days 00:00:00.092414,2,5,102,COMPLETE
13,13,0.920833,2026-04-14 20:46:57.583727,2026-04-14 20:46:57.679344,0 days 00:00:00.095617,2,9,84,COMPLETE
28,28,0.920833,2026-04-14 20:46:59.135038,2026-04-14 20:46:59.227281,0 days 00:00:00.092243,2,6,94,COMPLETE

In [21]:
# Train using optimal parameters
model_1 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_1.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=2,
                       min_samples_split=5, n_estimators=104, random_state=42)

In [22]:
y_pred = model_1.predict(X_test)

In [23]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       190
           1       0.64      0.95      0.77        19

    accuracy                           0.95       209
   macro avg       0.82      0.95      0.87       209
weighted avg       0.96      0.95      0.95       209

In [24]:
recall_model_report_df = classification_report(y_test, y_pred, output_dict=True)

## F1 as metric

In [25]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-04-14 20:47:06,523] A new study created in memory with name: no-name-e541dcc8-166e-40ed-a4f2-736ee9852759
[I 2026-04-14 20:47:06,597] Trial 0 finished with value: 0.6676210415809221 and parameters: {'n_estimators': 77, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.6676210415809221.
[I 2026-04-14 20:47:06,737] Trial 1 finished with value: 0.7644932844932846 and parameters: {'n_estimators': 132, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 1 with value: 0.7644932844932846.
[I 2026-04-14 20:47:06,815] Trial 2 finished with value: 0.7631317701905938 and parameters: {'n_estimators': 61, 'max_depth': 17, 'min_samples_split': 9}. Best is trial 1 with value: 0.7644932844932846.
[I 2026-04-14 20:47:06,923] Trial 3 finished with value: 0.7786243386243386 and parameters: {'n_estimators': 110, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 3 with value: 0.7786243386243386.
[I 2026-04-14 20:47:07,015] Trial 4 finished with value: 0.661411916854246 and parameters: {'n_estimators': 104, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 3 with value: 0.7786243386243386.
[I 2026-04-14 20:47:07,157] Trial 5 finished with value: 0.6212457571419567 and parameters: {'n_estimators': 161, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 3 with value: 0.7786243386243386.
[I 2026-04-14 20:47:07,251] Trial 6 finished with value: 0.6212457571419567 and parameters: {'n_estimators': 88, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 3 with value: 0.7786243386243386.
[I 2026-04-14 20:47:07,437] Trial 7 finished with value: 0.7820747579428795 and parameters: {'n_estimators': 179, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:07,546] Trial 8 finished with value: 0.7688630323924441 and parameters: {'n_estimators': 107, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:07,594] Trial 9 finished with value: 0.7695090828711517 and parameters: {'n_estimators': 35, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:07,809] Trial 10 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 198, 'max_depth': 28, 'min_samples_split': 2}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,011] Trial 11 finished with value: 0.7631317701905938 and parameters: {'n_estimators': 196, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,183] Trial 12 finished with value: 0.7752529823118058 and parameters: {'n_estimators': 155, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,214] Trial 13 finished with value: 0.736906126174419 and parameters: {'n_estimators': 14, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,385] Trial 14 finished with value: 0.7708832344126462 and parameters: {'n_estimators': 166, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,524] Trial 15 finished with value: 0.7723118058412176 and parameters: {'n_estimators': 132, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,666] Trial 16 finished with value: 0.7706184012066365 and parameters: {'n_estimators': 123, 'max_depth': 21, 'min_samples_split': 8}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:08,852] Trial 17 finished with value: 0.7819289157264685 and parameters: {'n_estimators': 176, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:09,024] Trial 18 finished with value: 0.7819289157264685 and parameters: {'n_estimators': 174, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:09,227] Trial 19 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 183, 'max_depth': 21, 'min_samples_split': 3}. Best is trial 7 with value: 0.7820747579428795.
[I 2026-04-14 20:47:09,382] Trial 20 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 149, 'max_depth': 11, 'min_samples_split': 4}. Best is trial 20 with value: 0.7873961467876274.
[I 2026-04-14 20:47:09,538] Trial 21 finished with value: 0.7559576719576718 and parameters: {'n_estimators': 148, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 20 with value: 0.7873961467876274.
[I 2026-04-14 20:47:09,725] Trial 22 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 185, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:09,879] Trial 23 finished with value: 0.7799095157715847 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:10,081] Trial 24 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 185, 'max_depth': 30, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:10,268] Trial 25 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 191, 'max_depth': 31, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:10,470] Trial 26 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 191, 'max_depth': 32, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:10,671] Trial 27 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 198, 'max_depth': 24, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:10,842] Trial 28 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 168, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,029] Trial 29 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 184, 'max_depth': 31, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,170] Trial 30 finished with value: 0.7606513056835636 and parameters: {'n_estimators': 135, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,357] Trial 31 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 185, 'max_depth': 32, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,557] Trial 32 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 186, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,729] Trial 33 finished with value: 0.7799095157715847 and parameters: {'n_estimators': 169, 'max_depth': 27, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,807] Trial 34 finished with value: 0.7735545314900153 and parameters: {'n_estimators': 70, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:11,963] Trial 35 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 139, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,181] Trial 36 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 200, 'max_depth': 23, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,320] Trial 37 finished with value: 0.7818047489381652 and parameters: {'n_estimators': 118, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,495] Trial 38 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 159, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,590] Trial 39 finished with value: 0.7660866229781037 and parameters: {'n_estimators': 85, 'max_depth': 27, 'min_samples_split': 6}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,776] Trial 40 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 176, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:12,979] Trial 41 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 184, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,176] Trial 42 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 187, 'max_depth': 28, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,377] Trial 43 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 192, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,549] Trial 44 finished with value: 0.7665973756662758 and parameters: {'n_estimators': 162, 'max_depth': 19, 'min_samples_split': 6}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,736] Trial 45 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 179, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,798] Trial 46 finished with value: 0.6940123924970838 and parameters: {'n_estimators': 46, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:13,984] Trial 47 finished with value: 0.7755178155178155 and parameters: {'n_estimators': 190, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:14,201] Trial 48 finished with value: 0.7819289157264685 and parameters: {'n_estimators': 169, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:14,310] Trial 49 finished with value: 0.776682555780933 and parameters: {'n_estimators': 96, 'max_depth': 23, 'min_samples_split': 6}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:14,479] Trial 50 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 157, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:14,666] Trial 51 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 174, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:14,837] Trial 52 finished with value: 0.7799095157715847 and parameters: {'n_estimators': 162, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,038] Trial 53 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 192, 'max_depth': 28, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,242] Trial 54 finished with value: 0.773326765188834 and parameters: {'n_estimators': 200, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,426] Trial 55 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 180, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,597] Trial 56 finished with value: 0.7735545314900153 and parameters: {'n_estimators': 156, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,753] Trial 57 finished with value: 0.773326765188834 and parameters: {'n_estimators': 142, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:15,941] Trial 58 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 185, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:16,151] Trial 59 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 193, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:16,307] Trial 60 finished with value: 0.6212457571419567 and parameters: {'n_estimators': 170, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:16,510] Trial 61 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 185, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:16,681] Trial 62 finished with value: 0.7562743777005237 and parameters: {'n_estimators': 181, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:16,869] Trial 63 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 174, 'max_depth': 26, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,058] Trial 64 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 195, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,231] Trial 65 finished with value: 0.7752529823118058 and parameters: {'n_estimators': 164, 'max_depth': 21, 'min_samples_split': 10}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,434] Trial 66 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 185, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,607] Trial 67 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 151, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,638] Trial 68 finished with value: 0.7488411385774469 and parameters: {'n_estimators': 15, 'max_depth': 24, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:17,826] Trial 69 finished with value: 0.7706184012066365 and parameters: {'n_estimators': 172, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:18,030] Trial 70 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 180, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:18,250] Trial 71 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 194, 'max_depth': 23, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:18,440] Trial 72 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 189, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:18,644] Trial 73 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 196, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:18,849] Trial 74 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 188, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,053] Trial 75 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,241] Trial 76 finished with value: 0.7564311977581623 and parameters: {'n_estimators': 178, 'max_depth': 26, 'min_samples_split': 7}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,415] Trial 77 finished with value: 0.773326765188834 and parameters: {'n_estimators': 167, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,557] Trial 78 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 126, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,760] Trial 79 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 190, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:19,948] Trial 80 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 183, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:20,136] Trial 81 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 180, 'max_depth': 28, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:20,326] Trial 82 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 177, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:20,532] Trial 83 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 194, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:20,705] Trial 84 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 160, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:20,895] Trial 85 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 173, 'max_depth': 23, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:21,083] Trial 86 finished with value: 0.7649523809523808 and parameters: {'n_estimators': 188, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:21,273] Trial 87 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 183, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:21,463] Trial 88 finished with value: 0.7739027149321267 and parameters: {'n_estimators': 166, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:21,634] Trial 89 finished with value: 0.780442057942058 and parameters: {'n_estimators': 177, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:21,854] Trial 90 finished with value: 0.773326765188834 and parameters: {'n_estimators': 197, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:22,028] Trial 91 finished with value: 0.7929346083260891 and parameters: {'n_estimators': 157, 'max_depth': 11, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:22,185] Trial 92 finished with value: 0.7819774275758048 and parameters: {'n_estimators': 142, 'max_depth': 12, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:22,375] Trial 93 finished with value: 0.7743181179221222 and parameters: {'n_estimators': 190, 'max_depth': 14, 'min_samples_split': 5}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:22,563] Trial 94 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 170, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.
[I 2026-04-14 20:47:22,751] Trial 95 finished with value: 0.7873961467876274 and parameters: {'n_estimators': 175, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 22 with value: 0.7929346083260891.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
32,32,0.792935,2026-04-14 20:47:11.357601,2026-04-14 20:47:11.557995,0 days 00:00:00.200394,21,4,186,COMPLETE
24,24,0.792935,2026-04-14 20:47:09.879923,2026-04-14 20:47:10.081522,0 days 00:00:00.201599,30,4,185,COMPLETE
25,25,0.792935,2026-04-14 20:47:10.081522,2026-04-14 20:47:10.268852,0 days 00:00:00.187330,31,4,191,COMPLETE
29,29,0.792935,2026-04-14 20:47:10.843338,2026-04-14 20:47:11.029315,0 days 00:00:00.185977,31,4,184,COMPLETE
22,22,0.792935,2026-04-14 20:47:09.538279,2026-04-14 20:47:09.725117,0 days 00:00:00.186838,15,4,185,COMPLETE

In [26]:
# Train using optimal parameters
model_2 = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model_2.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=21,
                       min_samples_split=4, n_estimators=186, random_state=42)

In [27]:
y_pred = model_2.predict(X_test)

In [28]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       190
           1       0.89      0.84      0.86        19

    accuracy                           0.98       209
   macro avg       0.94      0.92      0.93       209
weighted avg       0.98      0.98      0.98       209

In [29]:
f1_model_report_df = classification_report(y_test, y_pred, output_dict=True)

### Analyze reports

In [34]:
# 2. Convert and transpose
recall_report_df = pd.DataFrame(recall_model_report_df).transpose()
f1_report_df = pd.DataFrame(f1_model_report_df).transpose()

# 3. Combine multiple reports (e.g., adding a 'Model' column for identification)
combined_df = pd.concat([recall_report_df, f1_report_df], keys=['PPP RF optimized for Recall', 'PPP RF optimized for F1'])

In [35]:
combined_df

                                          precision    recall  f1-score  \
PPP RF optimized for Recall 0              0.994475  0.947368  0.970350
                            1              0.642857  0.947368  0.765957
                            accuracy       0.947368  0.947368  0.947368
                            macro avg      0.818666  0.947368  0.868154
                            weighted avg   0.962510  0.947368  0.951769
PPP RF optimized for F1     0              0.984293  0.989474  0.986877
                            1              0.888889  0.842105  0.864865
                            accuracy       0.976077  0.976077  0.976077
                            macro avg      0.936591  0.915789  0.925871
                            weighted avg   0.975620  0.976077  0.975785

                                             support
PPP RF optimized for Recall 0             190.000000
                            1              19.000000
                            accuracy        0.947368
                            macro avg     209.000000
                            weighted avg  209.000000
PPP RF optimized for F1     0             190.000000
                            1              19.000000
                            accuracy        0.976077
                            macro avg     209.000000
                            weighted avg  209.000000

In [32]:
# Recall model
importances = model_1.feature_importances_
feature_names = df.drop(columns='Fraud').columns
feature_imp_recall_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_recall_df

                          Feature  Gini Importance
24              ForgivenessAmount         0.204918
39            ForgivenessDate_int         0.165690
27             ForgivenPercentage         0.137547
2                      LoanStatus         0.116737
26              NotForgivenAmount         0.108818
40             LoanStatusDate_int         0.100746
38               DateApproved_int         0.032356
3                            Term         0.020419
37                PROCEED_Per_Job         0.016742
0                ProcessingMethod         0.015200
4           InitialApprovalAmount         0.013993
12                   JobsReported         0.010139
11                   ProjectState         0.009571
14                PAYROLL_PROCEED         0.008428
13              UTILITIES_PROCEED         0.006656
28                  TOTAL_PROCEED         0.006225
5           CurrentApprovalAmount         0.005717
10         BusinessAgeDescription         0.003858
20                   BusinessType         0.003182
6            ServicingLenderState         0.003127
29                   PROCEED_Diff         0.002856
21         OriginatingLenderState         0.002374
16                   RENT_PROCEED         0.002202
33               RENT_PROCEED_pct         0.000738
22                        Veteran         0.000570
35        HEALTH_CARE_PROCEED_pct         0.000425
1                   BorrowerState         0.000316
25                   ApprovalDiff         0.000241
8                HubzoneIndicator         0.000172
19          DEBT_INTEREST_PROCEED         0.000037
7             RuralUrbanIndicator         0.000000
9                    LMIIndicator         0.000000
15      MORTGAGE_INTEREST_PROCEED         0.000000
23                      NonProfit         0.000000
17         REFINANCE_EIDL_PROCEED         0.000000
18            HEALTH_CARE_PROCEED         0.000000
30          UTILITIES_PROCEED_pct         0.000000
32  MORTGAGE_INTEREST_PROCEED_pct         0.000000
31            PAYROLL_PROCEED_pct         0.000000
36      DEBT_INTEREST_PROCEED_pct         0.000000
34     REFINANCE_EIDL_PROCEED_pct         0.000000

In [33]:
# Recall model
importances = model_2.feature_importances_
feature_names = df.drop(columns='Fraud').columns
feature_imp_f1_df = pd.DataFrame({'Feature': feature_names, 'Gini Importance': importances}).sort_values(
    'Gini Importance', ascending=False)
feature_imp_f1_df

                          Feature  Gini Importance
39            ForgivenessDate_int     1.592659e-01
24              ForgivenessAmount     1.462004e-01
27             ForgivenPercentage     1.124539e-01
26              NotForgivenAmount     1.000095e-01
40             LoanStatusDate_int     9.282154e-02
2                      LoanStatus     7.414662e-02
38               DateApproved_int     4.951110e-02
37                PROCEED_Per_Job     2.814497e-02
3                            Term     2.322377e-02
5           CurrentApprovalAmount     2.206470e-02
4           InitialApprovalAmount     2.137037e-02
14                PAYROLL_PROCEED     1.876411e-02
12                   JobsReported     1.742577e-02
28                  TOTAL_PROCEED     1.677632e-02
0                ProcessingMethod     1.275709e-02
1                   BorrowerState     1.255410e-02
13              UTILITIES_PROCEED     1.255147e-02
29                   PROCEED_Diff     1.253085e-02
11                   ProjectState     1.240243e-02
21         OriginatingLenderState     9.362973e-03
6            ServicingLenderState     8.547983e-03
10         BusinessAgeDescription     7.360358e-03
20                   BusinessType     6.496224e-03
22                        Veteran     5.419831e-03
16                   RENT_PROCEED     4.924388e-03
33               RENT_PROCEED_pct     2.575244e-03
9                    LMIIndicator     2.247586e-03
8                HubzoneIndicator     1.756326e-03
25                   ApprovalDiff     1.210087e-03
30          UTILITIES_PROCEED_pct     1.158528e-03
18            HEALTH_CARE_PROCEED     8.849344e-04
31            PAYROLL_PROCEED_pct     8.206646e-04
7             RuralUrbanIndicator     6.495106e-04
35        HEALTH_CARE_PROCEED_pct     6.453763e-04
23                      NonProfit     3.759811e-04
36      DEBT_INTEREST_PROCEED_pct     3.018112e-04
19          DEBT_INTEREST_PROCEED     2.554959e-04
15      MORTGAGE_INTEREST_PROCEED     3.174803e-05
32  MORTGAGE_INTEREST_PROCEED_pct     2.281016e-17
34     REFINANCE_EIDL_PROCEED_pct     5.107520e-18
17         REFINANCE_EIDL_PROCEED     2.836864e-18